import { OUTCODE_CENTROIDS } from "./postcode";
import { IMAGE_CATEGORY_LABELS } from "@/constants/propertyTypes";
import type { Agent } from "@/types/agent";
import type {
  ImageCategory,
  Property,
  PropertyImage,
} from "@/types/property";

/**
 * Builds a gallery from the shared illustration set. `variant` (1-3) picks one
 * of three coordinated palettes so each property's photos look like one shoot.
 */
function gallery(
  propertyId: string,
  variant: 1 | 2 | 3,
  categories: ImageCategory[],
): PropertyImage[] {
  return categories.map((category, index) => ({
    id: `${propertyId}-img-${index + 1}`,
    src: `/images/properties/${category}-${variant}.svg`,
    category,
    alt: `${IMAGE_CATEGORY_LABELS[category]} at ${propertyId.replace(/-/g, " ")}`,
  }));
}

const FULL: ImageCategory[] = [
  "exterior",
  "living",
  "kitchen",
  "bedroom",
  "bathroom",
  "garden",
  "parking",
  "other",
];
const FLAT: ImageCategory[] = [
  "exterior",
  "living",
  "kitchen",
  "bedroom",
  "bathroom",
  "other",
];

export const agents: Agent[] = [
  {
    id: "harper-quinn",
    name: "Amara Okafor",
    agency: "Harper & Quinn",
    logo: "/images/agents/harper-quinn.svg",
    town: "London",
    postcode: "SW11 3QX",
    lat: OUTCODE_CENTROIDS.SW11.lat,
    lng: OUTCODE_CENTROIDS.SW11.lng,
    phone: "020 7946 0112",
    email: "amara@harperquinn.example",
    specialisations: ["sales", "lettings", "luxury"],
    areasCovered: ["Battersea", "Clapham", "Wandsworth", "Balham", "Nine Elms"],
    rating: 4.8,
    reviewCount: 214,
    reviews: [
      {
        author: "Priya S.",
        rating: 5,
        comment:
          "Amara found us a flat two streets from where we wanted, and handled the chain when our buyer wobbled. Calm throughout.",
        date: "2026-07-14",
      },
      {
        author: "Tom B.",
        rating: 4,
        comment:
          "Very responsive on viewings. Paperwork took a week longer than promised but she kept us updated.",
        date: "2026-05-02",
      },
    ],
    bio: "Eighteen years selling and letting south-west London riverside homes. Amara heads the Battersea office and personally handles every instruction above £750k.",
  },
  {
    id: "northgate",
    name: "Daniel Wright",
    agency: "Northgate Residential",
    logo: "/images/agents/northgate.svg",
    town: "Manchester",
    postcode: "M1 4BT",
    lat: OUTCODE_CENTROIDS.M1.lat,
    lng: OUTCODE_CENTROIDS.M1.lng,
    phone: "0161 496 0230",
    email: "daniel@northgateresi.example",
    specialisations: ["lettings", "new-builds", "student"],
    areasCovered: ["Manchester city centre", "Didsbury", "Chorlton", "Salford Quays"],
    rating: 4.6,
    reviewCount: 168,
    reviews: [
      {
        author: "Leah M.",
        rating: 5,
        comment: "Referencing was done in two days and the tenancy started on time.",
        date: "2026-08-21",
      },
      {
        author: "Adeel R.",
        rating: 4,
        comment: "Good knowledge of the new-build stock around Ancoats.",
        date: "2026-06-11",
      },
    ],
    bio: "Northgate specialises in city-centre lettings and off-plan apartments across Greater Manchester, with a dedicated student team each summer.",
  },
  {
    id: "beldon-clark",
    name: "Grace Fenwick",
    agency: "Beldon Clark",
    logo: "/images/agents/beldon-clark.svg",
    town: "Bristol",
    postcode: "BS8 1RG",
    lat: OUTCODE_CENTROIDS.BS8.lat,
    lng: OUTCODE_CENTROIDS.BS8.lng,
    phone: "0117 496 0088",
    email: "grace@beldonclark.example",
    specialisations: ["sales", "luxury"],
    areasCovered: ["Clifton", "Redland", "Cotham", "Bristol harbourside"],
    rating: 4.9,
    reviewCount: 96,
    reviews: [
      {
        author: "Jonathan H.",
        rating: 5,
        comment:
          "Sold a Georgian terrace in eleven days at asking. The photography made the difference.",
        date: "2026-09-01",
      },
    ],
    bio: "A small Clifton practice with a period-property focus. Grace has sold more listed buildings in BS8 than any other agent in the last five years.",
  },
  {
    id: "kestrel",
    name: "Rachel Boateng",
    agency: "Kestrel Homes",
    logo: "/images/agents/kestrel.svg",
    town: "Leeds",
    postcode: "LS6 2AE",
    lat: OUTCODE_CENTROIDS.LS6.lat,
    lng: OUTCODE_CENTROIDS.LS6.lng,
    phone: "0113 496 0417",
    email: "rachel@kestrelhomes.example",
    specialisations: ["lettings", "student", "sales"],
    areasCovered: ["Headingley", "Hyde Park", "Chapel Allerton", "Leeds city centre"],
    rating: 4.4,
    reviewCount: 302,
    reviews: [
      {
        author: "Sam O.",
        rating: 4,
        comment: "Big student portfolio, fast to arrange group viewings.",
        date: "2026-04-30",
      },
      {
        author: "Nicola D.",
        rating: 5,
        comment: "Deposit returned in full within a week of check-out.",
        date: "2026-08-05",
      },
    ],
    bio: "Kestrel manages just over 900 homes across north Leeds, split between student houses and professional lets.",
  },
  {
    id: "ashcombe",
    name: "Michael Osei",
    agency: "Ashcombe Property",
    logo: "/images/agents/ashcombe.svg",
    town: "Birmingham",
    postcode: "B15 2TT",
    lat: OUTCODE_CENTROIDS.B15.lat,
    lng: OUTCODE_CENTROIDS.B15.lng,
    phone: "0121 496 0654",
    email: "michael@ashcombeproperty.example",
    specialisations: ["sales", "new-builds", "commercial"],
    areasCovered: ["Edgbaston", "Harborne", "Moseley", "Birmingham city centre"],
    rating: 4.5,
    reviewCount: 141,
    reviews: [
      {
        author: "Farah K.",
        rating: 5,
        comment: "Straight-talking valuation, no inflated figure to win the instruction.",
        date: "2026-07-27",
      },
    ],
    bio: "Ashcombe covers residential sales and mixed-use investment across central Birmingham, with an in-house new-homes team.",
  },
  {
    id: "thistle-row",
    name: "Eilidh Ramsay",
    agency: "Thistle Row",
    logo: "/images/agents/thistle-row.svg",
    town: "Edinburgh",
    postcode: "EH3 6QG",
    lat: OUTCODE_CENTROIDS.EH3.lat,
    lng: OUTCODE_CENTROIDS.EH3.lng,
    phone: "0131 496 0290",
    email: "eilidh@thistlerow.example",
    specialisations: ["sales", "lettings"],
    areasCovered: ["New Town", "Stockbridge", "Bruntsfield", "Leith"],
    rating: 4.7,
    reviewCount: 122,
    reviews: [
      {
        author: "Callum W.",
        rating: 5,
        comment: "Handled the Home Report and closing date process brilliantly.",
        date: "2026-06-19",
      },
    ],
    bio: "Thistle Row works across Edinburgh's central conservation areas, covering both Scottish sales and private residential tenancies.",
  },
  {
    id: "seabright",
    name: "Olivia Marchetti",
    agency: "Seabright & Co",
    logo: "/images/agents/seabright.svg",
    town: "Brighton",
    postcode: "BN1 3XB",
    lat: OUTCODE_CENTROIDS.BN1.lat,
    lng: OUTCODE_CENTROIDS.BN1.lng,
    phone: "01273 496 020",
    email: "olivia@seabrightco.example",
    specialisations: ["lettings", "sales"],
    areasCovered: ["Brighton", "Hove", "Kemptown", "Preston Park"],
    rating: 4.3,
    reviewCount: 87,
    reviews: [
      {
        author: "Danny P.",
        rating: 4,
        comment: "Knows the seafront stock inside out. Fees are on the higher side.",
        date: "2026-03-16",
      },
    ],
    bio: "Seabright is an independent coastal agency covering Brighton and Hove, with a strong line in period conversions near the seafront.",
  },
  {
    id: "meridian",
    name: "Hassan Iqbal",
    agency: "Meridian Living",
    logo: "/images/agents/meridian.svg",
    town: "Cambridge",
    postcode: "CB1 2JD",
    lat: OUTCODE_CENTROIDS.CB1.lat,
    lng: OUTCODE_CENTROIDS.CB1.lng,
    phone: "01223 496 077",
    email: "hassan@meridianliving.example",
    specialisations: ["lettings", "new-builds", "sales"],
    areasCovered: ["Cambridge", "Trumpington", "Cherry Hinton", "Ely"],
    rating: 4.6,
    reviewCount: 133,
    reviews: [
      {
        author: "Dr. Anne L.",
        rating: 5,
        comment: "Arranged a corporate let for an incoming researcher at short notice.",
        date: "2026-09-08",
      },
    ],
    bio: "Meridian focuses on the Cambridge research and tech corridor, handling relocations, corporate lets and new-build sales.",
  },
];

interface Seed extends Omit<Property, "images" | "lat" | "lng"> {
  variant: 1 | 2 | 3;
  categories?: ImageCategory[];
}

const seeds: Seed[] = [
  {
    id: "battersea-riverside-loft",
    title: "Riverside warehouse loft with private terrace",
    intent: "rent",
    price: 3150,
    addressLine1: "Apartment 12, Corbett Wharf",
    addressLine2: "Lombard Road",
    town: "Battersea, London",
    postcode: "SW11 3RX",
    type: "flat",
    bedrooms: 2,
    bathrooms: 2,
    sizeSqFt: 1120,
    description:
      "A converted Victorian warehouse loft on the south bank, with 4.2m ceilings, exposed brick and steel-framed Crittall windows facing the river. The open living space runs the full width of the building and opens onto a 30ft private terrace. Both bedrooms are doubles with fitted storage; the principal has an en-suite with a walk-in shower. Secure underground parking for one car and a lift from the lobby. Chelsea Bridge and the Thames path are a two-minute walk.",
    availableFrom: "2026-10-15",
    furnished: "part-furnished",
    energyRating: "B",
    councilTaxBand: "E",
    depositWeeks: 5,
    agentId: "harper-quinn",
    listedAt: "2026-09-18",
    featured: true,
    variant: 1,
  },
  {
    id: "clifton-georgian-townhouse",
    title: "Grade II listed Georgian townhouse",
    intent: "buy",
    price: 1_250_000,
    addressLine1: "18 Vyvyan Terrace",
    town: "Clifton, Bristol",
    postcode: "BS8 3DG",
    type: "terraced",
    bedrooms: 5,
    bathrooms: 3,
    sizeSqFt: 2680,
    description:
      "One of the finest surviving terraces in Clifton, arranged over four floors with the original 1840s cornicing, shutters and cantilevered stone staircase intact. The kitchen-dining room occupies the garden level and opens to a walled south-facing courtyard. Five bedrooms including a full-floor principal suite. Resident permit parking and a short walk to the Suspension Bridge, Clifton Village and the Downs.",
    availableFrom: "2026-11-01",
    energyRating: "D",
    tenure: "freehold",
    councilTaxBand: "G",
    agentId: "beldon-clark",
    listedAt: "2026-09-12",
    featured: true,
    variant: 3,
  },
  {
    id: "didsbury-semi",
    title: "Extended 1930s semi with garden studio",
    intent: "buy",
    price: 585_000,
    addressLine1: "44 Elmsworth Avenue",
    town: "Didsbury, Manchester",
    postcode: "M20 2QT",
    type: "semi-detached",
    bedrooms: 4,
    bathrooms: 2,
    sizeSqFt: 1640,
    description:
      "A well-proportioned inter-war semi that has been thoughtfully extended to the rear, creating an open kitchen-family room with a glazed gable and bifolds onto the garden. Four bedrooms upstairs plus a converted loft room currently used as an office. The insulated garden studio has power and data. Driveway parking for two, and Didsbury Village and the Metrolink are within ten minutes on foot.",
    availableFrom: "2026-12-05",
    energyRating: "C",
    tenure: "freehold",
    councilTaxBand: "E",
    agentId: "northgate",
    listedAt: "2026-09-20",
    featured: true,
    variant: 2,
  },
  {
    id: "headingley-student-six",
    title: "Six-bedroom student house, all bills included",
    intent: "rent",
    price: 2_760,
    addressLine1: "9 Brudenell Mount",
    town: "Headingley, Leeds",
    postcode: "LS6 1HZ",
    type: "terraced",
    bedrooms: 6,
    bathrooms: 3,
    sizeSqFt: 1980,
    description:
      "A large back-to-back terrace arranged for group living, licensed as an HMO and fully compliant with current fire regulations. Six good-sized double bedrooms, each with a desk and double wardrobe, three shower rooms and two separate living spaces. Rent is quoted for the whole house and includes gas, electricity, water and broadband. Ten minutes' walk to the University of Leeds and directly on the 6 bus route.",
    availableFrom: "2027-07-01",
    furnished: "furnished",
    energyRating: "C",
    councilTaxBand: "A",
    depositWeeks: 5,
    agentId: "kestrel",
    listedAt: "2026-09-05",
    variant: 1,
  },
  {
    id: "edgbaston-penthouse",
    title: "Penthouse apartment overlooking the reservoir",
    intent: "buy",
    price: 725_000,
    addressLine1: "Penthouse, Calthorpe House",
    addressLine2: "Westbourne Road",
    town: "Edgbaston, Birmingham",
    postcode: "B15 3TR",
    type: "flat",
    bedrooms: 3,
    bathrooms: 2,
    sizeSqFt: 1480,
    description:
      "The top-floor apartment in a 2023 development, with a wraparound balcony taking in Edgbaston Reservoir and the city skyline. Underfloor heating throughout, an integrated Siemens kitchen and a utility room. Two allocated parking bays with an EV charger, plus a residents' gym on the ground floor. 990-year lease with a share of the freehold.",
    availableFrom: "2026-10-01",
    energyRating: "A",
    tenure: "leasehold",
    councilTaxBand: "F",
    agentId: "ashcombe",
    listedAt: "2026-09-22",
    featured: true,
    variant: 2,
  },
  {
    id: "new-town-flat",
    title: "First-floor drawing room flat in the New Town",
    intent: "rent",
    price: 2_100,
    addressLine1: "3/2 Dundas Street",
    town: "Edinburgh",
    postcode: "EH3 6QG",
    type: "flat",
    bedrooms: 2,
    bathrooms: 1,
    sizeSqFt: 980,
    description:
      "A classic New Town flat on the first floor, with the tall arched windows and original working shutters that define the drawing room. Two double bedrooms, a dining kitchen and a recently refitted bathroom with an overhead shower. Gas central heating and a shared rear drying green. Zoned permit parking and a five-minute walk to Princes Street.",
    availableFrom: "2026-11-10",
    furnished: "furnished",
    energyRating: "D",
    councilTaxBand: "D",
    depositWeeks: 5,
    agentId: "thistle-row",
    listedAt: "2026-09-16",
    variant: 3,
  },
  {
    id: "kemptown-seafront",
    title: "Seafront regency conversion with sea views",
    intent: "buy",
    price: 465_000,
    addressLine1: "Flat 4, Marine Parade",
    town: "Kemptown, Brighton",
    postcode: "BN1 1GG",
    type: "flat",
    bedrooms: 2,
    bathrooms: 1,
    sizeSqFt: 860,
    description:
      "A bright second-floor conversion in a stuccoed Regency terrace directly facing the sea. The living room has a bay window with unbroken views to the horizon, and the second bedroom works equally well as a study. Recently rewired, with a new combi boiler in 2025. Share of freehold with a well-run residents' company and a modest annual service charge.",
    availableFrom: "2026-10-20",
    energyRating: "D",
    tenure: "leasehold",
    councilTaxBand: "C",
    agentId: "seabright",
    listedAt: "2026-08-29",
    variant: 1,
  },
  {
    id: "trumpington-newbuild",
    title: "Brand-new three-bedroom family house",
    intent: "buy",
    price: 540_000,
    addressLine1: "Plot 27, Wren Fields",
    addressLine2: "Hauxton Road",
    town: "Trumpington, Cambridge",
    postcode: "CB1 8LP",
    type: "detached",
    bedrooms: 3,
    bathrooms: 2,
    sizeSqFt: 1310,
    description:
      "A newly completed detached house on a low-density development south of the city, built to an EPC A standard with an air-source heat pump, solar array and triple glazing. Open-plan kitchen-diner with French doors to a turfed rear garden, separate sitting room and a downstairs cloakroom. Ten-year structural warranty. The Trumpington park-and-ride and the guided busway are a short cycle away.",
    availableFrom: "2026-10-30",
    energyRating: "A",
    tenure: "freehold",
    councilTaxBand: "E",
    agentId: "meridian",
    listedAt: "2026-09-24",
    featured: true,
    variant: 3,
  },
  {
    id: "peckham-warehouse-studio",
    title: "Studio apartment in a converted print works",
    intent: "rent",
    price: 1_395,
    addressLine1: "Unit 6, Rye Print Works",
    town: "Peckham, London",
    postcode: "SE15 4TP",
    type: "studio",
    bedrooms: 1,
    bathrooms: 1,
    sizeSqFt: 480,
    description:
      "A compact but well-planned studio in a 1920s print works, with a raised sleeping platform, full-height industrial windows and a galley kitchen with integrated appliances. Communal roof terrace and a bike store in the courtyard. Peckham Rye station is six minutes on foot for services to London Bridge and Victoria.",
    availableFrom: "2026-10-05",
    furnished: "furnished",
    energyRating: "C",
    councilTaxBand: "B",
    depositWeeks: 5,
    agentId: "harper-quinn",
    listedAt: "2026-09-19",
    variant: 2,
    categories: ["exterior", "living", "kitchen", "bathroom", "other"],
  },
  {
    id: "canary-wharf-tower",
    title: "High-floor apartment with dock views",
    intent: "rent",
    price: 2_650,
    addressLine1: "Apt 2804, Meridian Tower",
    addressLine2: "Marsh Wall",
    town: "Canary Wharf, London",
    postcode: "E14 9XL",
    type: "flat",
    bedrooms: 2,
    bathrooms: 2,
    sizeSqFt: 790,
    description:
      "A 28th-floor apartment with floor-to-ceiling glazing on two aspects, looking over South Dock and the City beyond. Both bedrooms are doubles with built-in wardrobes and the principal has an en-suite. Building amenities include a 24-hour concierge, gym, pool and residents' lounge. Two minutes to South Quay DLR, eight to the Elizabeth line.",
    availableFrom: "2026-10-01",
    furnished: "furnished",
    energyRating: "B",
    councilTaxBand: "E",
    depositWeeks: 5,
    agentId: "harper-quinn",
    listedAt: "2026-09-21",
    variant: 3,
  },
  {
    id: "chorlton-terrace",
    title: "Two-bedroom terrace off Beech Road",
    intent: "buy",
    price: 325_000,
    addressLine1: "12 Ivygreen Road",
    town: "Chorlton, Manchester",
    postcode: "M20 1AB",
    type: "terraced",
    bedrooms: 2,
    bathrooms: 1,
    sizeSqFt: 820,
    description:
      "A tidy red-brick terrace a street back from Beech Road, with the front room and dining room knocked through and a galley kitchen leading to the yard. Two doubles upstairs and a modern bathroom with a rainfall shower. Loft is boarded with a fixed ladder. Ideal first purchase, with the bars and delis of Chorlton on the doorstep.",
    availableFrom: "2026-11-15",
    energyRating: "D",
    tenure: "freehold",
    councilTaxBand: "B",
    agentId: "northgate",
    listedAt: "2026-09-02",
    variant: 1,
  },
  {
    id: "jesmond-flat",
    title: "Tyneside flat with a private garden",
    intent: "rent",
    price: 995,
    addressLine1: "Ground Floor, 27 Osborne Gardens",
    town: "Jesmond, Newcastle",
    postcode: "NE2 2AR",
    type: "flat",
    bedrooms: 2,
    bathrooms: 1,
    sizeSqFt: 760,
    description:
      "A classic Tyneside flat with its own front door and sole use of the rear garden. High ceilings, a bay-fronted living room and two double bedrooms. The kitchen was refitted in 2024 with an integrated washer-dryer and dishwasher. Osborne Road and Jesmond Metro are both within five minutes.",
    availableFrom: "2026-10-12",
    furnished: "unfurnished",
    energyRating: "C",
    councilTaxBand: "B",
    depositWeeks: 5,
    agentId: "kestrel",
    listedAt: "2026-09-10",
    variant: 2,
  },
  {
    id: "ecclesall-detached",
    title: "Detached family home backing onto the woods",
    intent: "buy",
    price: 695_000,
    addressLine1: "5 Whirlow Grange Close",
    town: "Ecclesall, Sheffield",
    postcode: "S11 9NF",
    type: "detached",
    bedrooms: 5,
    bathrooms: 3,
    sizeSqFt: 2340,
    description:
      "A substantial 1970s detached house on a quiet close, backing directly onto Ecclesall Woods. Five bedrooms, three of them en-suite, and a double-height entrance hall. The rear garden is mature and entirely private, with a raised deck catching the afternoon sun. Double garage plus off-street parking for three. Catchment for two of the city's strongest secondary schools.",
    availableFrom: "2027-01-10",
    energyRating: "C",
    tenure: "freehold",
    councilTaxBand: "F",
    agentId: "kestrel",
    listedAt: "2026-08-25",
    variant: 3,
  },
  {
    id: "cardiff-bay-apartment",
    title: "Waterside apartment with a balcony",
    intent: "rent",
    price: 1_150,
    addressLine1: "Flat 21, Hafod Quay",
    town: "Cardiff",
    postcode: "CF11 0SN",
    type: "flat",
    bedrooms: 2,
    bathrooms: 2,
    sizeSqFt: 720,
    description:
      "A third-floor apartment in a well-maintained waterside block, with a balcony facing the bay. Open-plan living space, two doubles and two bathrooms including an en-suite. Allocated undercroft parking and a secure entry system. Walking distance to the Wales Millennium Centre and Mermaid Quay.",
    availableFrom: "2026-10-08",
    furnished: "part-furnished",
    energyRating: "B",
    councilTaxBand: "D",
    depositWeeks: 5,
    agentId: "meridian",
    listedAt: "2026-09-14",
    variant: 1,
  },
  {
    id: "oxford-north-victorian",
    title: "Victorian villa in North Oxford",
    intent: "buy",
    price: 1_450_000,
    addressLine1: "22 Frenchay Road",
    town: "Oxford",
    postcode: "OX2 6TG",
    type: "detached",
    bedrooms: 6,
    bathrooms: 4,
    sizeSqFt: 3120,
    description:
      "An imposing North Oxford villa of the 1880s, set behind a deep front garden on one of the area's most sought-after roads. Generous reception rooms with original fireplaces, a large kitchen-breakfast room and a cellar. Six bedrooms over two upper floors. The west-facing garden runs to nearly 140ft with mature planting and a coach house currently used as a studio.",
    availableFrom: "2027-02-01",
    energyRating: "E",
    tenure: "freehold",
    councilTaxBand: "H",
    agentId: "beldon-clark",
    listedAt: "2026-09-08",
    variant: 2,
  },
  {
    id: "reading-town-flat",
    title: "Modern one-bedroom flat near the station",
    intent: "rent",
    price: 1_050,
    addressLine1: "Flat 8, Kennet House",
    addressLine2: "Kings Road",
    town: "Reading",
    postcode: "RG1 3BX",
    type: "flat",
    bedrooms: 1,
    bathrooms: 1,
    sizeSqFt: 540,
    description:
      "A neat one-bedroom flat in a 2019 building, four minutes from Reading station and the Elizabeth line. Open-plan kitchen-living room with integrated appliances, a double bedroom with fitted wardrobes and a shower room. Video entry, lift access and a shared courtyard garden.",
    availableFrom: "2026-10-02",
    furnished: "furnished",
    energyRating: "B",
    councilTaxBand: "C",
    depositWeeks: 5,
    agentId: "meridian",
    listedAt: "2026-09-23",
    variant: 3,
    categories: ["exterior", "living", "kitchen", "bedroom", "bathroom"],
  },
  {
    id: "york-mews-cottage",
    title: "Mews cottage inside the city walls",
    intent: "buy",
    price: 395_000,
    addressLine1: "4 Gray's Court Mews",
    town: "York",
    postcode: "YO1 7JN",
    type: "terraced",
    bedrooms: 2,
    bathrooms: 1,
    sizeSqFt: 740,
    description:
      "A charming cottage tucked down a cobbled mews within the city walls, moments from the Minster. Exposed beams, a wood-burning stove and a compact but complete kitchen. Two bedrooms upstairs and a shower room. A small courtyard garden catches the morning sun. No onward chain.",
    availableFrom: "2026-11-20",
    energyRating: "E",
    tenure: "freehold",
    councilTaxBand: "C",
    agentId: "kestrel",
    listedAt: "2026-08-18",
    variant: 1,
    categories: ["exterior", "living", "kitchen", "bedroom", "bathroom", "garden"],
  },
  {
    id: "glasgow-west-end",
    title: "West End main door with original features",
    intent: "rent",
    price: 1_450,
    addressLine1: "0/1, 14 Kersland Street",
    town: "Hillhead, Glasgow",
    postcode: "G12 8BW",
    type: "flat",
    bedrooms: 3,
    bathrooms: 1,
    sizeSqFt: 1180,
    description:
      "A spacious main-door flat in a blonde sandstone tenement, with ornate cornicing, a bay window and three genuine double bedrooms. Large dining kitchen at the rear and a family bathroom with both a bath and a separate shower. Shared back garden and a residents' parking zone. Byres Road and Hillhead subway are both under five minutes.",
    availableFrom: "2026-10-25",
    furnished: "unfurnished",
    energyRating: "D",
    councilTaxBand: "E",
    depositWeeks: 5,
    agentId: "thistle-row",
    listedAt: "2026-09-11",
    variant: 2,
  },
  {
    id: "milton-keynes-bungalow",
    title: "Single-storey bungalow with a large plot",
    intent: "buy",
    price: 410_000,
    addressLine1: "7 Longcroft Lane",
    town: "Milton Keynes",
    postcode: "MK9 3LD",
    type: "bungalow",
    bedrooms: 3,
    bathrooms: 2,
    sizeSqFt: 1250,
    description:
      "A well-kept detached bungalow on a generous corner plot, offering level access throughout and scope to extend subject to consent. Three bedrooms, a wet room and a separate family bathroom. The conservatory looks over a lawned garden of around a fifth of an acre. Garage and a wide driveway.",
    availableFrom: "2026-12-01",
    energyRating: "D",
    tenure: "freehold",
    councilTaxBand: "D",
    agentId: "ashcombe",
    listedAt: "2026-09-06",
    variant: 3,
  },
  {
    id: "leicester-city-flat",
    title: "Loft-style apartment in the Cultural Quarter",
    intent: "rent",
    price: 875,
    addressLine1: "Apt 15, The Hosiery",
    town: "Leicester",
    postcode: "LE2 7DR",
    type: "flat",
    bedrooms: 1,
    bathrooms: 1,
    sizeSqFt: 610,
    description:
      "A converted hosiery factory in the Cultural Quarter, retaining cast-iron columns and original timber floors. Double-height living space with a mezzanine bedroom, plus a separate shower room. Bike storage and a communal courtyard. Curve theatre and Leicester station are both within ten minutes on foot.",
    availableFrom: "2026-10-18",
    furnished: "part-furnished",
    energyRating: "C",
    councilTaxBand: "B",
    depositWeeks: 5,
    agentId: "ashcombe",
    listedAt: "2026-09-13",
    variant: 1,
    categories: ["exterior", "living", "kitchen", "bedroom", "bathroom"],
  },
  {
    id: "southampton-semi",
    title: "Refurbished semi close to the common",
    intent: "buy",
    price: 349_950,
    addressLine1: "31 Rockstone Lane",
    town: "Southampton",
    postcode: "SO15 2EP",
    type: "semi-detached",
    bedrooms: 3,
    bathrooms: 2,
    sizeSqFt: 1080,
    description:
      "Fully refurbished in 2025, with new wiring, plumbing, windows and a replastered interior throughout. Three bedrooms, a downstairs shower room and a first-floor bathroom. The kitchen-diner opens to a low-maintenance rear garden. Southampton Common is a two-minute walk and the station is a fifteen-minute one.",
    availableFrom: "2026-10-28",
    energyRating: "B",
    tenure: "freehold",
    councilTaxBand: "C",
    agentId: "seabright",
    listedAt: "2026-09-17",
    variant: 2,
  },
  {
    id: "croydon-family-house",
    title: "Four-bedroom house with off-street parking",
    intent: "rent",
    price: 2_250,
    addressLine1: "88 Brackendale Road",
    town: "Croydon",
    postcode: "CR0 6HE",
    type: "semi-detached",
    bedrooms: 4,
    bathrooms: 2,
    sizeSqFt: 1420,
    description:
      "A comfortable family house on a residential road, with two reception rooms, a conservatory and a 60ft rear garden. Four bedrooms including two large doubles, a family bathroom and a separate WC. Driveway parking for two cars. East Croydon is a twelve-minute bus ride for fast services to London Bridge and Victoria.",
    availableFrom: "2026-11-05",
    furnished: "unfurnished",
    energyRating: "C",
    councilTaxBand: "E",
    depositWeeks: 5,
    agentId: "harper-quinn",
    listedAt: "2026-09-04",
    variant: 3,
  },
  {
    id: "bath-crescent-apartment",
    title: "Apartment in a Bath stone crescent",
    intent: "buy",
    price: 615_000,
    addressLine1: "Flat 2, Lansdown Crescent",
    town: "Bath",
    postcode: "BA1 5EX",
    type: "flat",
    bedrooms: 2,
    bathrooms: 2,
    sizeSqFt: 1040,
    description:
      "A piano nobile apartment in one of Bath's great Georgian crescents, with three tall sash windows framing an uninterrupted view across the city to the hills beyond. Two double bedrooms, one en-suite, and a well-proportioned drawing room with the original marble fireplace. Share of freehold and use of the communal gardens.",
    availableFrom: "2026-11-25",
    energyRating: "E",
    tenure: "leasehold",
    councilTaxBand: "F",
    agentId: "beldon-clark",
    listedAt: "2026-08-31",
    variant: 1,
    categories: ["exterior", "living", "kitchen", "bedroom", "bathroom", "garden"],
  },
  {
    id: "exeter-new-house",
    title: "Energy-efficient townhouse over three floors",
    intent: "buy",
    price: 375_000,
    addressLine1: "Plot 11, Alder Green",
    town: "Exeter",
    postcode: "EX4 8QT",
    type: "terraced",
    bedrooms: 4,
    bathrooms: 3,
    sizeSqFt: 1380,
    description:
      "A three-storey townhouse on a new development north of the city, designed around a top-floor principal suite with a dormer window and a dressing area. Kitchen-diner and utility on the ground floor with the living room above. Air-source heat pump, MVHR and solar PV keep running costs very low. Allocated parking with an EV point.",
    availableFrom: "2026-10-16",
    energyRating: "A",
    tenure: "freehold",
    councilTaxBand: "D",
    agentId: "meridian",
    listedAt: "2026-09-25",
    variant: 2,
  },
];

export const properties: Property[] = seeds.map(({ variant, categories, ...rest }) => {
  const centroid = OUTCODE_CENTROIDS[rest.postcode.split(" ")[0]];
  if (!centroid) {
    throw new Error(`No centroid for outcode in postcode "${rest.postcode}"`);
  }

  // Nudge each listing off the outcode centroid so map pins do not stack.
  const jitter = (seed: string, scale: number) => {
    let hash = 0;
    for (let i = 0; i < seed.length; i++) hash = (hash * 31 + seed.charCodeAt(i)) | 0;
    return ((hash % 1000) / 1000 - 0.5) * scale;
  };

  const defaults =
    rest.type === "flat" || rest.type === "studio" ? FLAT : FULL;

  return {
    ...rest,
    lat: centroid.lat + jitter(rest.id, 0.03),
    lng: centroid.lng + jitter(`${rest.id}x`, 0.05),
    images: gallery(rest.id, variant, categories ?? defaults),
  };
});
